name: chess

targets:
  chess:
    info:
      path: chess/Info.plist
      properties:
        UISupportedInterfaceOrientations: [ UIInterfaceOrientationPortrait ]
        UILaunchStoryboardName: LaunchScreen


    type: application
    platform: iOS
    deploymentTarget: 15.5
    sources: [Sources]
    settings:
      TARGETED_DEVICE_FAMILY: 1
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "at.htl.chess"
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1


settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.2
    ENABLE_BITCODE: NO
    SWIFT_VERSION: 5.2
  configs:
    Release:
      ENABLE_BITCODE: YES